name: MSA 빌드 및 Dockerhub에 Push

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  SHA: ${{ github.sha }}

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: drama 이미지 빌드 & 푸시
        run: |
          docker build -t $DOCKERHUB_USERNAME/drama:$SHA ./drama
          docker push $DOCKERHUB_USERNAME/drama:$SHA

      - name: episode 이미지 빌드 & 푸시
        run: |
          docker build -t $DOCKERHUB_USERNAME/episode:$SHA ./episode
          docker push $DOCKERHUB_USERNAME/episode:$SHA

      - name: stream 이미지 빌드 & 푸시
        run: |
          docker build -t $DOCKERHUB_USERNAME/stream:$SHA ./stream
          docker push $DOCKERHUB_USERNAME/stream:$SHA
