server:
  port: 8001

spring:
  application:
    name: drama
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/daenamu_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #  cloud:
  #    loadbalancer:
  #      ribbon:
  #        enabled: false
  #      discovery:
  #        enabled: true
  cloud:
    discovery:
      client:
        simple:
          instances:
            episode:
              - uri: http://episode:8002
  #  config:
  #    import: application-secret.yml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0