server:
  port: 8003
spring:
  application:
    name: stream
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/daenamu3_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #  config:
  #    import: classpath:application-secret.yml
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}

management:
  tracing:
    sampling:
      probability: 1.0